databases:
  - name: TimeTableGenerator
    databaseName: TimeTableGenerator
    user: TimeTableGenerator
    plan: free

services:
  - type: web
    name: TimeTableGenerator
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: TimeTableGenerator
          property: connectionString
      - key: 249244127561a319075299cf00d85899
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default