default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>

development:
  <<: *default
  database: timetablegenerator
  username: postgres
  password: password
  host: localhost
  port: 5432

# test:
#   <<: *default
#   database: your_database_name_test
#   username: your_username
#   password: your_password
#   host: localhost
#   port: 5432

# production:
#   <<: *default
#   database: your_database_name_production
#   username: your_username
#   password: your_password
#   host: your_production_host
#   port: your_production_port
