default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>

development:
  <<: *default
  database: timetablegenerator
  username: postgres
  password: password
  host: localhost
  port: 5432

# test:
#   <<: *default
#   database: your_database_name_test
#   username: your_username
#   password: your_password
#   host: localhost
#   port: 5432

# production:
#   <<: *default
#   url: <%= ENV['DATABASE_URL'] %>
#
# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: my_app_render_production
  username: my_app_render
  password: <%= ENV['MY_APP_RENDER_DATABASE_PASSWORD'] %>
